server:
  port: ${PORT:8080}
spring:
  application:
    name: ${APPLICATION_NAME:student-service}
  datasource:
    url: ${DATABASE_URI:jdbc:postgresql://localhost:5432/students}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
asurepro:
  app:
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}
    jwtSecret: ${JWT_EXPIRATION_MS:asurepro$#20##!21}
    jwtCookieName: ${JWT_COOKIE_NAME:asureprouser}